CREATE TABLE IF NOT EXISTS customers (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  name NVARCHAR(255) NOT NULL,
  email NVARCHAR(255),
  phone NVARCHAR(255),
  company NVARCHAR(255),
  address NVARCHAR(MAX),
  created_at DATETIMEOFFSET DEFAULT GETUTCDATE(),
  updated_at DATETIMEOFFSET DEFAULT GETUTCDATE()
);

CREATE TABLE IF NOT EXISTS services (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  name NVARCHAR(255) NOT NULL,
  description NVARCHAR(MAX),
  unit_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
  unit NVARCHAR(50) DEFAULT 'unit',
  created_at DATETIMEOFFSET DEFAULT GETUTCDATE(),
  updated_at DATETIMEOFFSET DEFAULT GETUTCDATE()
);

CREATE TABLE IF NOT EXISTS quotations (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  customer_id UNIQUEIDENTIFIER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  quotation_number NVARCHAR(255) UNIQUE NOT NULL,
  date DATE DEFAULT CAST(GETUTCDATE() AS DATE),
  valid_until DATE,
  status NVARCHAR(50) DEFAULT 'draft',
  notes NVARCHAR(MAX),
  total DECIMAL(10, 2) DEFAULT 0,
  created_at DATETIMEOFFSET DEFAULT GETUTCDATE(),
  updated_at DATETIMEOFFSET DEFAULT GETUTCDATE()
);

CREATE TABLE IF NOT EXISTS quotation_items (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  quotation_id UNIQUEIDENTIFIER NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
  service_id UNIQUEIDENTIFIER REFERENCES services(id) ON DELETE SET NULL,
  description NVARCHAR(MAX) NOT NULL,
  quantity DECIMAL(10, 2) NOT NULL DEFAULT 1,
  unit_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
  total DECIMAL(10, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS invoices (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  customer_id UNIQUEIDENTIFIER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  quotation_id UNIQUEIDENTIFIER REFERENCES quotations(id) ON DELETE SET NULL,
  invoice_number NVARCHAR(255) UNIQUE NOT NULL,
  date DATE DEFAULT CAST(GETUTCDATE() AS DATE),
  due_date DATE,
  status NVARCHAR(50) DEFAULT 'draft',
  notes NVARCHAR(MAX),
  total DECIMAL(10, 2) DEFAULT 0,
  created_at DATETIMEOFFSET DEFAULT GETUTCDATE(),
  updated_at DATETIMEOFFSET DEFAULT GETUTCDATE()
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  invoice_id UNIQUEIDENTIFIER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  service_id UNIQUEIDENTIFIER REFERENCES services(id) ON DELETE SET NULL,
  description NVARCHAR(MAX) NOT NULL,
  quantity DECIMAL(10, 2) NOT NULL DEFAULT 1,
  unit_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
  total DECIMAL(10, 2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_quotations_customer_id ON quotations(customer_id);
CREATE INDEX IF NOT EXISTS idx_quotations_status ON quotations(status);
CREATE INDEX IF NOT EXISTS idx_quotation_items_quotation_id ON quotation_items(quotation_id);
CREATE INDEX IF NOT EXISTS idx_invoices_customer_id ON invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice_id ON invoice_items(invoice_id);
